import { jsPDF } from 'jspdf';
import { CitizenProfile, EligibilityResult } from '../types';

export function generateCitizenEligibilityPdf(profile: CitizenProfile, results: EligibilityResult[]) {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString('en-IN');

  // Header Banner
  doc.setFillColor(30, 58, 138); // Deep Navy
  doc.rect(0, 0, 210, 32, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('YOJANA MITRA AI', 14, 18);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Official Government Scheme Eligibility Assessment Report', 14, 25);
  doc.text(`Generated: ${timestamp}`, 140, 25);

  let y = 42;

  // Citizen Profile Section
  doc.setFillColor(243, 244, 246);
  doc.roundedRect(14, y, 182, 36, 3, 3, 'F');

  doc.setTextColor(17, 24, 39);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('CITIZEN PROFILE SUMMARY', 20, y + 8);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Name: ${profile.name || 'Citizen'} | Age: ${profile.age || 'N/A'} | Gender: ${profile.gender || 'N/A'}`, 20, y + 16);
  doc.text(`State: ${profile.state || 'India'} | District: ${profile.district || 'N/A'} | Caste: ${profile.caste || 'General'}`, 20, y + 23);
  doc.text(`Annual Income: ₹${profile.annualIncome ? profile.annualIncome.toLocaleString('en-IN') : 'Not specified'} | Occupation: ${profile.occupation || 'N/A'}`, 20, y + 30);

  y += 44;

  // Eligible Schemes Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(30, 58, 138);
  doc.text('TOP ELIGIBLE GOVERNMENT SCHEMES', 14, y);

  y += 8;

  const topResults = results.filter(r => r.score >= 50).slice(0, 6);

  if (topResults.length === 0) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text('No high matching schemes found based on current profile details.', 14, y);
    y += 10;
  } else {
    topResults.forEach((res, index) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }

      const scheme = res.scheme;
      const statusColor = res.score >= 80 ? [16, 185, 129] : [245, 158, 11]; // Emerald or Amber

      doc.setFillColor(249, 250, 251);
      doc.roundedRect(14, y, 182, 32, 2, 2, 'F');
      doc.setDrawColor(229, 231, 235);
      doc.roundedRect(14, y, 182, 32, 2, 2, 'S');

      // Score Badge
      doc.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
      doc.roundedRect(165, y + 4, 26, 8, 2, 2, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text(`${res.score}% Match`, 167, y + 9.5);

      doc.setTextColor(17, 24, 39);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text(`${index + 1}. ${scheme.name}`, 18, y + 8);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(75, 85, 99);
      doc.text(`Benefits: ${scheme.benefits.slice(0, 85)}...`, 18, y + 15);
      doc.text(`Required Documents: ${scheme.requiredDocuments.join(', ').slice(0, 85)}...`, 18, y + 21);
      doc.text(`Portal: ${scheme.officialWebsite} | Helpline: ${scheme.helpline}`, 18, y + 27);

      y += 36;
    });
  }

  // Footer / Verification Notice
  if (y > 240) {
    doc.addPage();
    y = 20;
  }

  y += 10;
  doc.setLineWidth(0.5);
  doc.setDrawColor(209, 213, 219);
  doc.line(14, y, 196, y);

  y += 8;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(30, 58, 138);
  doc.text('VERIFICATION & NEXT STEPS', 14, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text('1. Visit your nearest MeeSeva or Common Service Center (CSC) with original copies of Aadhaar, Income & Ration Cards.', 14, y + 6);
  doc.text('2. Verification of land records and income slab will be conducted by District Revenue Nodal Officers.', 14, y + 11);
  doc.text('3. This report is generated by Yojana Mitra AI for citizen guidance. Verify official guidelines at scheme portals.', 14, y + 16);

  // Save File
  const filename = `Yojana_Mitra_Report_${profile.name ? profile.name.replace(/\s+/g, '_') : 'Citizen'}.pdf`;
  doc.save(filename);
}
